version: "3.8"

volumes:
  database:
  media:

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    stop_signal: SIGINT
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: taigaio/taiga5:latest
    command:
      - migrate
      # Make sure this command is run only during the initial setup as it will
      # overwrite existing data.
      - populate-db
      - run-server
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:${PORT:-8888}/api/v1/
    ports:
      - ${PORT:-8888}:8080
    stop_signal: SIGHUP
    volumes:
      - ./docker-compose/settings.py:/etc/opt/taiga-back/settings.py:ro
      - media:/srv/taiga-back/media
